name: Discord Webhook Notification

on:
    pull_request:
        types: [opened, reopened, synchronize, edited]
        branches:
            - "**"

jobs:
    notify-pull_request:
        runs-on: ubuntu-latest
        env:
            DISCORD_GREEN: "3066993" # Green color
        steps:
            - name: Send Discord Webhook for Pull Request
              uses: sarisia/actions-status-discord@v1
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  status: ${{ job.status }}
                  title: "Pull Request Notification"
                  description: |
                      A pull request has been opened or updated by **${{ github.actor }}**.

                      **Branch:** `${{ github.head_ref }}`
                      **Repository:** [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})

                      👉 [View Pull Request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
                  color: "${{ env.DISCORD_GREEN }}"
                  username: "GitHub Actions Bot"
                  avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
