name: Discord Webhook Notification

on:
    push:
        branches:
            - '**'

jobs:
    notify-push:
        runs-on: ubuntu-latest
        steps:
            - name: Send Discord Webhook for Push
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
              run: |
                curl -H "Content-Type: application/json" \
                  -d "{\"content\": \"A push has been made to branch: ${{ github.ref_name }} by ${{ github.actor }}.\"}" \
                  $DISCORD_WEBHOOK_URL

